# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

highlight:
  enable: true

jquery:
  js: //code.jquery.com/jquery-3.2.1.min.js
  migrate: //code.jquery.com/jquery-migrate-1.4.1.min.js

bootstrap:
  js: //cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/js/bootstrap.min.js
  css: //cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css

fancybox:
  enable: true
  js: //cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.20/jquery.fancybox.min.js
  css: //cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.20/jquery.fancybox.min.css

# Sidebar
sidebar: none
search:
  enable: true
  url: //google.com/search
  keyword: q

widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
